/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tema38;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author franc
 */
public class JFrame_Arrendamientos extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Arrendamientos
     */
    
    private String sucursal;
    private int cantidadDias = 1;
    public JFrame_Arrendamientos() {
        initComponents();
        
        sucursal = null;
        actualizarListaSucursales();
        actualizarListaClientes();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Clientes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton_CrearArrendamiento = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_EquiposDeSucursal = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_Sucursales = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jSlider_dias = new javax.swing.JSlider();
        jLabel_cantidadDias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jList_Clientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_ClientesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList_Clientes);

        jLabel1.setText("Seleccionar Cliente:");

        jButton_CrearArrendamiento.setText("Generar nuevo arrendamiento");

        jScrollPane2.setViewportView(jList_EquiposDeSucursal);

        jLabel2.setText("Seleccionar Sucursal:");

        jLabel3.setText("Seleccionar Equipo:");

        jList_Sucursales.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_SucursalesValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jList_Sucursales);

        jLabel4.setText("Dias:");

        jSlider_dias.setMaximum(30);
        jSlider_dias.setMinimum(1);
        jSlider_dias.setValue(1);
        jSlider_dias.setAlignmentX(0.0F);
        jSlider_dias.setAlignmentY(0.0F);
        jSlider_dias.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_diasStateChanged(evt);
            }
        });

        jLabel_cantidadDias.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jButton_CrearArrendamiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel_cantidadDias, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider_dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(345, 345, 345))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane3))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CrearArrendamiento)
                    .addComponent(jLabel4)
                    .addComponent(jSlider_dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_cantidadDias))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList_ClientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_ClientesValueChanged
       
        //Evento que se llama cuando se apreta un nuevo cliente
        
        
    }//GEN-LAST:event_jList_ClientesValueChanged

    private void jSlider_diasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_diasStateChanged
        // Llamado cada vez que slider cambia el valor
        
        cantidadDias = jSlider_dias.getValue();
        String dias = (""+cantidadDias);
        jLabel_cantidadDias.setText(dias);
    }//GEN-LAST:event_jSlider_diasStateChanged

    private void jList_SucursalesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_SucursalesValueChanged
        //Llamado cada vez que se selecciona una nueva sucursal
        //Actualizar actual
        
        sucursal = jList_Sucursales.getSelectedValue();
        
        actualizarListaEquipos();
    }//GEN-LAST:event_jList_SucursalesValueChanged

    /**
     * @param args the command line arguments
     */
    
    
    private void actualizarListaSucursales(){
        
        //  Obtener la lista de nombres desde sistema
        ArrayList<String> nombres = SistemaArrendamiento.getInstance().getNombresSucursales();
        DefaultListModel<String> modelo = new DefaultListModel<>();
        jList_Sucursales.setModel(modelo);
    
     
    //  Llenar el modelo con los nombres
    for (String nombre : nombres) {
        modelo.addElement(nombre);
    }
    }
    
    private void actualizarListaClientes(){
        //  Obtener la lista de nombres desde sistema
        ArrayList<String> nombres = SistemaArrendamiento.getInstance().getNombresClientes();
        DefaultListModel<String> modeloCliente = new DefaultListModel<>();
        jList_Clientes.setModel(modeloCliente);
    
     
        //  Llenar el modelo con los nombres
        for (String nombre : nombres) {
            modeloCliente.addElement(nombre);
        }
    }
    
    private void actualizarListaEquipos(){
        if(sucursal==null){
            return;
        }
        //solo opera si sucursal es valida
        //obtiene lista de equipos para esta y los carga en pantalla
        Sucursal sucursalActual = SistemaArrendamiento.getInstance().getSucursal(sucursal);
        
        ArrayList<Object> inventario = sucursalActual.getEquipos();
        DefaultListModel<Object> modeloInventario = new DefaultListModel<>();
        jList_EquiposDeSucursal.setModel(modeloInventario);
        //  Llenar el modelo con los nombres
        for (Object equipo : inventario) {
            modeloInventario.addElement(equipo);
        }
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Arrendamientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Arrendamientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Arrendamientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Arrendamientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Arrendamientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CrearArrendamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_cantidadDias;
    private javax.swing.JList<String> jList_Clientes;
    private javax.swing.JList<Object> jList_EquiposDeSucursal;
    private javax.swing.JList<String> jList_Sucursales;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider_dias;
    // End of variables declaration//GEN-END:variables
}
