/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tema38;

/**
 *
 * @author franc
 */
public class JFrame_Clientes extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Clients
     */
    public JFrame_Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_Buscarcliente1 = new javax.swing.JTextArea();
        jButton_Listarclientes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Listaclientes = new javax.swing.JTextArea();
        jButton_BuscarclienteRut = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_Buscarcliente = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea_Buscarcliente_Apellido = new javax.swing.JTextArea();
        jButton_BuscarclienteNombre = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea_Buscarcliente_Nombre = new javax.swing.JTextArea();
        jButton_AgregarCliente = new javax.swing.JButton();
        jTextField_NuevoCliente_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_NuevoCliente_apellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_NuevoCliente_rut = new javax.swing.JTextField();
        jLabel_succesAgregar = new javax.swing.JLabel();

        jTextArea_Buscarcliente1.setColumns(20);
        jTextArea_Buscarcliente1.setRows(5);
        jScrollPane4.setViewportView(jTextArea_Buscarcliente1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_Listarclientes.setText("Listar Clientes");
        jButton_Listarclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ListarclientesMouseClicked(evt);
            }
        });

        jTextArea_Listaclientes.setEditable(false);
        jTextArea_Listaclientes.setColumns(20);
        jTextArea_Listaclientes.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Listaclientes);

        jScrollPane2.setViewportView(jScrollPane1);

        jButton_BuscarclienteRut.setText("BuscarCliente por Rut");
        jButton_BuscarclienteRut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_BuscarclienteRutMouseClicked(evt);
            }
        });
        jButton_BuscarclienteRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarclienteRutActionPerformed(evt);
            }
        });

        jTextArea_Buscarcliente.setColumns(20);
        jTextArea_Buscarcliente.setRows(5);
        jScrollPane3.setViewportView(jTextArea_Buscarcliente);

        jTextArea_Buscarcliente_Apellido.setColumns(20);
        jTextArea_Buscarcliente_Apellido.setRows(5);
        jScrollPane5.setViewportView(jTextArea_Buscarcliente_Apellido);
        jTextArea_Buscarcliente_Apellido.getAccessibleContext().setAccessibleName("apellido...");

        jButton_BuscarclienteNombre.setText("BuscarCliente por nombre y apellido");
        jButton_BuscarclienteNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_BuscarclienteNombreMouseClicked(evt);
            }
        });
        jButton_BuscarclienteNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarclienteNombreActionPerformed(evt);
            }
        });

        jTextArea_Buscarcliente_Nombre.setColumns(20);
        jTextArea_Buscarcliente_Nombre.setRows(5);
        jScrollPane6.setViewportView(jTextArea_Buscarcliente_Nombre);
        jTextArea_Buscarcliente_Nombre.getAccessibleContext().setAccessibleName("nombre...");

        jButton_AgregarCliente.setText("Agregar Cliente");
        jButton_AgregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_AgregarClienteMouseClicked(evt);
            }
        });

        jTextField_NuevoCliente_nombre.setToolTipText("Nombre");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jTextField_NuevoCliente_apellido.setToolTipText("Nombre");

        jLabel3.setText("Rut:");

        jTextField_NuevoCliente_rut.setToolTipText("Nombre");

        jLabel_succesAgregar.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Listarclientes)
                            .addComponent(jButton_BuscarclienteRut)
                            .addComponent(jButton_BuscarclienteNombre))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_succesAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_AgregarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jTextField_NuevoCliente_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_NuevoCliente_apellido))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_NuevoCliente_rut, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton_Listarclientes)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_BuscarclienteRut)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_BuscarclienteNombre)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AgregarCliente)
                    .addComponent(jTextField_NuevoCliente_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_NuevoCliente_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_NuevoCliente_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_succesAgregar)))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ListarclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ListarclientesMouseClicked
        // Listar clientes dentro del text panel, llamando a metodo de sistemaArrendamiento
        jTextArea_Listaclientes.setText(SistemaArrendamiento.getInstance().getListaClientes_ventana());
    }//GEN-LAST:event_jButton_ListarclientesMouseClicked

    private void jButton_BuscarclienteRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarclienteRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_BuscarclienteRutActionPerformed

    private void jButton_BuscarclienteRutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_BuscarclienteRutMouseClicked
      
        //Buscar cliente por rut
        Cliente clienteBuscado = SistemaArrendamiento.getInstance().buscarCliente(jTextArea_Buscarcliente.getText());
        
         jTextArea_Listaclientes.setText(clienteBuscado.getNombre()+ " - " + clienteBuscado.getApellido() + " - Rut : " + clienteBuscado.getRut()); 
    }//GEN-LAST:event_jButton_BuscarclienteRutMouseClicked
    
    private void jButton_BuscarclienteNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_BuscarclienteNombreMouseClicked
        
        //Buscar cliente por nombre y apellido
         Cliente clienteBuscado = SistemaArrendamiento.getInstance().buscarCliente(jTextArea_Buscarcliente_Nombre.getText(), jTextArea_Buscarcliente_Apellido.getText());
         jTextArea_Listaclientes.setText(clienteBuscado.getNombre()+ " - " + clienteBuscado.getApellido() + " - Rut : " + clienteBuscado.getRut());
    }//GEN-LAST:event_jButton_BuscarclienteNombreMouseClicked

    private void jButton_BuscarclienteNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarclienteNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_BuscarclienteNombreActionPerformed

    private void jButton_AgregarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AgregarClienteMouseClicked
       
        //Agregar cliente con parametros de rut, nombre y apellido
        
        String nombre = jTextField_NuevoCliente_nombre.getText();
        String apellido = jTextField_NuevoCliente_apellido.getText();
        String rut = jTextField_NuevoCliente_rut.getText();
        
        jLabel_succesAgregar.setText(SistemaArrendamiento.getInstance().agregarCliente_ventana(nombre, apellido, rut)); 
        
    }//GEN-LAST:event_jButton_AgregarClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AgregarCliente;
    private javax.swing.JButton jButton_BuscarclienteNombre;
    private javax.swing.JButton jButton_BuscarclienteRut;
    private javax.swing.JButton jButton_Listarclientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_succesAgregar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea_Buscarcliente;
    private javax.swing.JTextArea jTextArea_Buscarcliente1;
    private javax.swing.JTextArea jTextArea_Buscarcliente_Apellido;
    private javax.swing.JTextArea jTextArea_Buscarcliente_Nombre;
    private javax.swing.JTextArea jTextArea_Listaclientes;
    private javax.swing.JTextField jTextField_NuevoCliente_apellido;
    private javax.swing.JTextField jTextField_NuevoCliente_nombre;
    private javax.swing.JTextField jTextField_NuevoCliente_rut;
    // End of variables declaration//GEN-END:variables
}
